name: Daily Melbourne Incident Processing

on:
  schedule:
    - cron: "0 4 * * *"  # Runs daily at 1 PM Melbourne time (UTC+4)
  workflow_dispatch:  # Allows manual execution

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Fetch latest code
        run: git pull origin main  # Ensure it pulls the latest changes

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Pipeline
        run: python "project_melbourne(31_01).py"

      - name: Commit and Push Results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto update results"
          git push
